name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: checkboxes
    id: packages
    attributes:
      label: Packages Affected
      description: Select the packages relevant to this feature.
      options:
        - label: "@santi020k/eslint-config-basic"
        - label: "@santi020k/eslint-config-core"
        - label: "@santi020k/eslint-config-typescript"
        - label: "@santi020k/eslint-config-react"
        - label: "@santi020k/eslint-config-next"
        - label: "@santi020k/eslint-config-astro"
        - label: "@santi020k/eslint-config-expo"

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
